### ISSUE TITLE
Keep failing while trying to enhancing.

### ISSUE THREAD

**Issue by onacit** [datanucleus/datanucleus-maven-plugin#9]
I'm trying to use DataNucleus with Maven.
```xl
          <plugin>
            <groupId>org.datanucleus</groupId>
            <artifactId>datanucleus-maven-plugin</artifactId>
            <version>5.0.2</version>
            <configuration>
              <api>JPA</api>
              <persistenceUnitName>examplePU</persistenceUnitName>
              <!--<log4jConfiguration>${basedir}/log4j.properties</log4jConfiguration>-->
              <verbose>true</verbose>
            </configuration>
            <executions>
              <execution>
                <phase>process-classes</phase>
                <goals>
                  <goal>enhance</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
```
And I only get this.
```
[ERROR] --------------------
[ERROR]  Standard error from the DataNucleus tool + org.datanucleus.enhancer.DataNucleusEnhancer :
[ERROR] --------------------
[ERROR] Error: Could not find or load main class org.datanucleus.enhancer.DataNucleusEnhancer
```
The `-X` shows this
```
[ERROR] Failed to execute goal org.datanucleus:datanucleus-maven-plugin:5.0.2:enhance (default) on project java-ee-example1-entities: The DataNucleus tool org.datanucleus.enhancer.DataNucleusEnhancer exited with a non-null exit code. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.datanucleus:datanucleus-maven-plugin:5.0.2:enhance (default) on project java-ee-example1-entities: The DataNucleus tool org.datanucleus.enhancer.DataNucleusEnhancer exited with a non-null exit code.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: The DataNucleus tool org.datanucleus.enhancer.DataNucleusEnhancer exited with a non-null exit code.
        at org.datanucleus.maven.AbstractDataNucleusMojo.executeCommandLine(AbstractDataNucleusMojo.java:282)
        at org.datanucleus.maven.AbstractEnhancerMojo.enhance(AbstractEnhancerMojo.java:223)
        at org.datanucleus.maven.AbstractEnhancerMojo.executeDataNucleusTool(AbstractEnhancerMojo.java:81)
        at org.datanucleus.maven.AbstractDataNucleusMojo.execute(AbstractDataNucleusMojo.java:126)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
```

**Comment by andyjefferson** [comment]
Firstly you have failed to provide a testcase that demonstrates anything, and secondly the message tells you the problem. 
Could not find or load main class org.datanucleus.enhancer.DataNucleusEnhancer

so you haven't put datanucleus-core in the CLASSPATH, and without an enhancer it will struggle to enhance!

**Comment by markthornton** [comment]
Perhaps you should update the documentation because the plugin configuration shown above is exactly that used in the documentation and as the OP has found it DOES NOT WORK.
Secondly why does the plugin not include a dependency on datanucleus-core to ensure that it is in the classpath used for plugin execution. Presumably because the versions of the plugin and core are not aligned.

**Comment by markthornton** [comment]
This suffices to run the enhancer goal:
`            <plugin>
                <groupId>org.datanucleus</groupId>
                <artifactId>datanucleus-maven-plugin</artifactId>
                <version>${datanucleus.plugin.version}</version>
                <configuration>
                    <api>JPA</api>
                    <persistenceUnitName>Accounts</persistenceUnitName>
                    
                    <verbose>true</verbose>
                </configuration>
                <dependencies>
				  	<dependency>
				  		<groupId>org.datanucleus</groupId>
				  		<artifactId>datanucleus-core</artifactId>
				  		<version>${datanucleus.version}</version>
				  		<scope>runtime</scope>
				  	</dependency>
				  	<dependency>
				  		<groupId>org.datanucleus</groupId>
				  		<artifactId>datanucleus-api-jpa</artifactId>
				  		<version>${datanucleus.version}</version>
				  		<scope>runtime</scope>
				  	</dependency>
                </dependencies>
                <executions>
                    <execution>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>enhance</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
`
With properties
datanucleus.plugin.version: 5.0.2
datanucleus.version 5.1.4

Note that the latest version, 5.1.5, does NOT work due to the datanucleus-api-jpa artifact being missing from maven central.

**Comment by andyjefferson** [comment]
Before saying what people should do, perhaps take the time to quote the actual PAGE of the documentation that you are referring to, then there is basis for comment. This issue was raised without the required testcase that demonstrates anything and so nothing can be done without that; sadly the original poster couldn't manage to come back with that, despite the issue tracker and docs providing a template.

If something is documentation then it should be raised against the requisite DOCUMENTATION project, such as https://github.com/datanucleus/docs-accessplatform  and then it is easy for you to provide a PULL REQUEST with whatever you think is needing to be updated.


> due to the datanucleus-api-jpa artifact being missing from maven central

If something is not released then it is not "missing". It doesn't exist. All plugins are independently versionaed, as they should be, and always will be.

**Comment by markthornton** [comment]
http://www.datanucleus.org:15080/products/accessplatform_5_1/jpa/tools.html#_enhancement_and_schematool

The plugin does not inherit the code dependencies (for compile/test).

Independent versioning is surprisingly uncommon in the maven world. In my experience most projects release a full set of artefacts for each version even if some are identical to the previous version. This avoids the problem of documenting what is a consistent set for each release.

**Comment by markthornton** [comment]
> Note that this plugin step will automatically try to bring in the latest applicable version of datanucleus-core for use by the enhancer. It does this since you don’t need to have datanucleus-core in your POM for compilation/enhancement.

From the same page. Does not appear to be true of the current plugin.

Edit: The plugin POM file declares datanucleus-core as a provided dependency, and thus must be declared in the users POM file with a specific version.
